services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - 8000:8000/tcp
    environment:
      DEBUG: False
    env_file:
      - ./Backend/.env

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - 3000:3000/tcp
    # Edit the API URL at ./Frontend/next.config.ts
    depends_on:
      - backend